import { Geist, Geist_Mono } from "next/font/google";
    import localFont from 'next/font/local';
import 'bootstrap/dist/css/bootstrap.min.css';
import '../style/main.scss';
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/navbar/Navbar";

const athinaRegular = localFont({
      src: '@/../../../public/fonts/Athina-Regular.otf', 
      display: 'swap', 
    subsets: ["latin"],

    });

const HarmondSemiBold = localFont({
      src: '@/../../../public/fonts/Harmond-SemBdItaCond.otf', 
      display: 'swap', 
    subsets: ["latin"],

    });


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${athinaRegular} ${HarmondSemiBold}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
